[2025-05-29 11:44:55,885] ERROR django.request Internal Server Error: /add_leading_record/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 71, in add_leading_record
    return render(request, 'leading/add_leading_record.html',
                  {'form': form, 'user_groups': user_groups, 'is_superuser': is_superuser})
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'add_physical_location' not found. 'add_physical_location' is not a valid view function or pattern name.
[2025-05-29 11:44:55,919] ERROR django.server "GET /add_leading_record/ HTTP/1.1" 500 145
[2025-05-29 11:44:58,292] ERROR django.request Internal Server Error: /add_leading_record/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 71, in add_leading_record
    return render(request, 'leading/add_leading_record.html',
                  {'form': form, 'user_groups': user_groups, 'is_superuser': is_superuser})
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'add_physical_location' not found. 'add_physical_location' is not a valid view function or pattern name.
[2025-05-29 11:44:58,301] ERROR django.server "GET /add_leading_record/ HTTP/1.1" 500 145
[2025-05-29 11:45:00,083] ERROR django.request Internal Server Error: /add_leading_record/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 71, in add_leading_record
    return render(request, 'leading/add_leading_record.html',
                  {'form': form, 'user_groups': user_groups, 'is_superuser': is_superuser})
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'add_physical_location' not found. 'add_physical_location' is not a valid view function or pattern name.
[2025-05-29 11:45:00,093] ERROR django.server "GET /add_leading_record/ HTTP/1.1" 500 145
[2025-05-29 11:45:56,495] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:45:56,525] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
[2025-05-29 11:45:58,012] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:45:58,023] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
[2025-05-29 11:46:01,978] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:46:01,987] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
[2025-05-29 11:46:02,737] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:46:02,748] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
[2025-05-29 11:46:05,046] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:46:05,058] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
[2025-05-29 11:46:07,645] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:46:07,658] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
[2025-05-29 11:46:07,952] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:46:07,968] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
[2025-05-29 11:46:10,370] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:46:10,382] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
[2025-05-29 11:46:10,698] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:46:10,710] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
[2025-05-29 11:46:10,906] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:46:10,921] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
[2025-05-29 11:46:11,094] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:46:11,120] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
[2025-05-29 11:46:14,093] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:46:14,104] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
[2025-05-29 11:46:14,283] ERROR django.request Internal Server Error: /add-physical-location/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 32, in add_physical_location
    return JsonResponse({
           ^^^^^^^^^^^^
NameError: name 'JsonResponse' is not defined. Did you mean: 'HttpResponse'?
[2025-05-29 11:46:14,298] ERROR django.server "POST /add-physical-location/ HTTP/1.1" 500 145
