[2025-05-21 14:09:47,630] ERROR django.request Internal Server Error: /get_bom_details/
[2025-05-21 14:09:47,631] ERROR django.server "POST /get_bom_details/ HTTP/1.1" 500 477
[2025-05-21 14:09:51,071] ERROR django.request Internal Server Error: /search_product/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
pyodbc.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (0) (SQLSetConnectAttr(SQL_ATTR_AUTOCOMMIT)); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]The connection is broken and recovery is not possible. The client driver attempted to recover the connection one or more times and all attempts failed. Increase the value of ConnectRetryCount to increase the number of recovery attempts. (0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\PRODUCTION\views.py", line 148, in search_product
    with connections['readonly_db'].cursor() as cursor:
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 316, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 261, in _cursor
    conn = super()._cursor()
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 292, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
django.db.utils.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (0) (SQLSetConnectAttr(SQL_ATTR_AUTOCOMMIT)); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]The connection is broken and recovery is not possible. The client driver attempted to recover the connection one or more times and all attempts failed. Increase the value of ConnectRetryCount to increase the number of recovery attempts. (0)')
[2025-05-21 14:09:51,099] ERROR django.server "GET /search_product/?search_type=stage_name&fg_filter=2%2C4%2C6%20TRIMETHYL%20PHENYL%20ACETYL%20CHLORIDE HTTP/1.1" 500 145
[2025-05-21 14:10:01,965] ERROR django.request Internal Server Error: /search_product/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
pyodbc.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (0) (SQLSetConnectAttr(SQL_ATTR_AUTOCOMMIT)); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]The connection is broken and recovery is not possible. The client driver attempted to recover the connection one or more times and all attempts failed. Increase the value of ConnectRetryCount to increase the number of recovery attempts. (0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\PRODUCTION\views.py", line 148, in search_product
    with connections['readonly_db'].cursor() as cursor:
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 316, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 261, in _cursor
    conn = super()._cursor()
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 292, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
django.db.utils.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (0) (SQLSetConnectAttr(SQL_ATTR_AUTOCOMMIT)); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]The connection is broken and recovery is not possible. The client driver attempted to recover the connection one or more times and all attempts failed. Increase the value of ConnectRetryCount to increase the number of recovery attempts. (0)')
[2025-05-21 14:10:01,972] ERROR django.server "GET /search_product/?search_type=fg_name HTTP/1.1" 500 145
[2025-05-21 14:10:07,792] ERROR django.request Internal Server Error: /search_product/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
pyodbc.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (0) (SQLSetConnectAttr(SQL_ATTR_AUTOCOMMIT)); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]The connection is broken and recovery is not possible. The client driver attempted to recover the connection one or more times and all attempts failed. Increase the value of ConnectRetryCount to increase the number of recovery attempts. (0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\PRODUCTION\views.py", line 148, in search_product
    with connections['readonly_db'].cursor() as cursor:
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 316, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 261, in _cursor
    conn = super()._cursor()
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 292, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
django.db.utils.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (0) (SQLSetConnectAttr(SQL_ATTR_AUTOCOMMIT)); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]The connection is broken and recovery is not possible. The client driver attempted to recover the connection one or more times and all attempts failed. Increase the value of ConnectRetryCount to increase the number of recovery attempts. (0)')
[2025-05-21 14:10:07,801] ERROR django.server "GET /search_product/?term=2%2C&search_type=fg_name HTTP/1.1" 500 145
[2025-05-21 14:10:08,337] ERROR django.request Internal Server Error: /search_product/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
pyodbc.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (0) (SQLSetConnectAttr(SQL_ATTR_AUTOCOMMIT)); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]The connection is broken and recovery is not possible. The client driver attempted to recover the connection one or more times and all attempts failed. Increase the value of ConnectRetryCount to increase the number of recovery attempts. (0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\PRODUCTION\views.py", line 148, in search_product
    with connections['readonly_db'].cursor() as cursor:
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 316, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 261, in _cursor
    conn = super()._cursor()
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 292, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
django.db.utils.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (0) (SQLSetConnectAttr(SQL_ATTR_AUTOCOMMIT)); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]The connection is broken and recovery is not possible. The client driver attempted to recover the connection one or more times and all attempts failed. Increase the value of ConnectRetryCount to increase the number of recovery attempts. (0)')
[2025-05-21 14:10:08,352] ERROR django.server "GET /search_product/?term=2%2C4%2C&search_type=fg_name HTTP/1.1" 500 145
[2025-05-21 14:10:14,123] ERROR django.request Internal Server Error: /search_batch/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
pyodbc.InterfaceError: ('28000', '[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'TEST-SERVER\\Administrator\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "eresOCSPL" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'TEST-SERVER\\Administrator\'. (18456); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "eresOCSPL" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\PRODUCTION\views.py", line 227, in search_batch
    with connections['readonly_db'].cursor() as cursor:
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 316, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 261, in _cursor
    conn = super()._cursor()
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 292, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
django.db.utils.InterfaceError: ('28000', '[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'TEST-SERVER\\Administrator\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "eresOCSPL" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'TEST-SERVER\\Administrator\'. (18456); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "eresOCSPL" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0)')
[2025-05-21 14:10:14,140] ERROR django.server "GET /search_batch/?stage_name=2%2C4%2C6%20TMBCL%20STAGE-I HTTP/1.1" 500 145
[2025-05-21 14:10:30,661] ERROR django.request Internal Server Error: /search_product/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
pyodbc.InterfaceError: ('28000', '[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'TEST-SERVER\\Administrator\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "eresOCSPL" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'TEST-SERVER\\Administrator\'. (18456); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "eresOCSPL" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\PRODUCTION\views.py", line 148, in search_product
    with connections['readonly_db'].cursor() as cursor:
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 316, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 261, in _cursor
    conn = super()._cursor()
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 292, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
django.db.utils.InterfaceError: ('28000', '[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'TEST-SERVER\\Administrator\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "eresOCSPL" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'TEST-SERVER\\Administrator\'. (18456); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "eresOCSPL" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0)')
[2025-05-21 14:10:30,675] ERROR django.server "GET /search_product/?search_type=fg_name HTTP/1.1" 500 145
[2025-05-21 14:10:33,908] ERROR django.request Internal Server Error: /search_product/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
pyodbc.InterfaceError: ('28000', '[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'TEST-SERVER\\Administrator\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "eresOCSPL" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'TEST-SERVER\\Administrator\'. (18456); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "eresOCSPL" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\PRODUCTION\views.py", line 148, in search_product
    with connections['readonly_db'].cursor() as cursor:
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 316, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 261, in _cursor
    conn = super()._cursor()
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 292, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\mssql\base.py", line 368, in get_new_connection
    conn = Database.connect(connstr, **args)
django.db.utils.InterfaceError: ('28000', '[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'TEST-SERVER\\Administrator\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "eresOCSPL" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'TEST-SERVER\\Administrator\'. (18456); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "eresOCSPL" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0)')
[2025-05-21 14:10:33,916] ERROR django.server "GET /search_product/?term=2%2C4%2C6&search_type=fg_name HTTP/1.1" 500 145
[2025-05-22 13:14:05,889] ERROR django.request Internal Server Error: /view_leading/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 97, in view_leading_records
    return render(request, 'leading/view_leading.html', context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'leading_chart_summary' not found. 'leading_chart_summary' is not a valid view function or pattern name.
[2025-05-22 13:14:06,118] ERROR django.server "GET /view_leading/ HTTP/1.1" 500 145
[2025-05-22 13:14:08,063] ERROR django.request Internal Server Error: /view_leading/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 97, in view_leading_records
    return render(request, 'leading/view_leading.html', context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'leading_chart_summary' not found. 'leading_chart_summary' is not a valid view function or pattern name.
[2025-05-22 13:14:08,096] ERROR django.server "GET /view_leading/ HTTP/1.1" 500 145
[2025-05-22 13:14:16,869] ERROR django.request Internal Server Error: /view_leading/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 97, in view_leading_records
    return render(request, 'leading/view_leading.html', context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'leading_chart_summary' not found. 'leading_chart_summary' is not a valid view function or pattern name.
[2025-05-22 13:14:16,896] ERROR django.server "GET /view_leading/ HTTP/1.1" 500 145
[2025-05-22 13:15:09,153] ERROR django.request Internal Server Error: /view_leading/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 97, in view_leading_records
    return render(request, 'leading/view_leading.html', context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'leading_chart_summary' not found. 'leading_chart_summary' is not a valid view function or pattern name.
[2025-05-22 13:15:09,166] ERROR django.server "GET /view_leading/ HTTP/1.1" 500 145
[2025-05-22 13:15:10,463] ERROR django.request Internal Server Error: /view_leading/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 97, in view_leading_records
    return render(request, 'leading/view_leading.html', context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'leading_chart_summary' not found. 'leading_chart_summary' is not a valid view function or pattern name.
[2025-05-22 13:15:10,473] ERROR django.server "GET /view_leading/ HTTP/1.1" 500 145
[2025-05-22 13:15:22,460] ERROR django.request Internal Server Error: /view_leading/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 97, in view_leading_records
    return render(request, 'leading/view_leading.html', context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'leading_chart_summary' not found. 'leading_chart_summary' is not a valid view function or pattern name.
[2025-05-22 13:15:22,476] ERROR django.server "GET /view_leading/ HTTP/1.1" 500 145
[2025-05-22 13:15:24,243] ERROR django.request Internal Server Error: /view_leading/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 97, in view_leading_records
    return render(request, 'leading/view_leading.html', context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'leading_chart_summary' not found. 'leading_chart_summary' is not a valid view function or pattern name.
[2025-05-22 13:15:24,291] ERROR django.server "GET /view_leading/ HTTP/1.1" 500 145
[2025-05-22 13:15:25,434] ERROR django.request Internal Server Error: /view_leading/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 97, in view_leading_records
    return render(request, 'leading/view_leading.html', context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'leading_chart_summary' not found. 'leading_chart_summary' is not a valid view function or pattern name.
[2025-05-22 13:15:25,444] ERROR django.server "GET /view_leading/ HTTP/1.1" 500 145
[2025-05-22 13:15:27,042] ERROR django.request Internal Server Error: /view_leading/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 97, in view_leading_records
    return render(request, 'leading/view_leading.html', context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'leading_chart_summary' not found. 'leading_chart_summary' is not a valid view function or pattern name.
[2025-05-22 13:15:27,050] ERROR django.server "GET /view_leading/ HTTP/1.1" 500 145
[2025-05-22 13:15:40,174] ERROR django.request Internal Server Error: /view_leading/
Traceback (most recent call last):
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "L:\oneSource_Live\oneSource\EHS\views.py", line 97, in view_leading_records
    return render(request, 'leading/view_leading.html', context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\oneSource_Live\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'leading_chart_summary' not found. 'leading_chart_summary' is not a valid view function or pattern name.
[2025-05-22 13:15:40,185] ERROR django.server "GET /view_leading/ HTTP/1.1" 500 145
